services:
  - type: web
    name: finance-backend
    env: node
    rootDir: finance-backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
    plan: free
